version: "2"

services:
  zookeeper:
    image: bobrik/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1

  marathon:
    image: mesosphere/marathon:v1.4.3
    hostname: marathon
    environment:
      MARATHON_MASTER: zk://zookeeper:2181/mesos
      MARATHON_ZK: zk://zookeeper:2181/mesos
    ports:
      - 8080:8080
    depends_on:
      - mesos-master

  mesos-master:
    image: mesosphere/mesos-master:1.2.0
    hostname: mesosmaster
    environment:
      MESOS_ZK: zk://zookeeper:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log
      MESOS_HOSTNAME: localhost
      LIBPROCESS_IP: "0.0.0.0"
    ports:
      - 5050:5050
    depends_on:
      - zookeeper

  mesos-worker-one:
    image: mesosphere/mesos-slave:1.2.0
    hostname: mesosworkerone
    pid: host
    environment:
      MESOS_MASTER: zk://zookeeper:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: mesosworkerone
      MESOS_WORK_DIR: /tmp/mesos
      LIBPROCESS_IP: "0.0.0.0"
    ports:
      - 5051:5051
    volumes:
      # Workaround for mac: download and link docker executable
      - ./bin/docker:/usr/bin/docker
      - /tmp/mesos:/tmp/mesos
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mesos-master

  # mesos-worker-two:
  #   image: mesosphere/mesos-slave:1.2.0
  #   hostname: mesosworkertwo
  #   pid: host
  #   environment:
  #     MESOS_MASTER: zk://zookeeper:2181/mesos
  #     MESOS_CONTAINERIZERS: docker,mesos
  #     MESOS_PORT: 5052
  #     MESOS_RESOURCES: ports(*):[12000-12999]
  #     MESOS_HOSTNAME: mesosworkertwo
  #     MESOS_WORK_DIR: /tmp/mesos
  #     LIBPROCESS_IP: "0.0.0.0"
  #   ports:
  #     - 5052:5052
  #   volumes:
  #     # Workaround for mac: download and link docker executable
  #     - ./bin/docker:/usr/bin/docker
  #     - /tmp/mesos:/tmp/mesos
  #     - /sys/fs/cgroup:/sys/fs/cgroup
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - mesos-master

  # chronos:
  #   image: mesosphere/chronos:v3.0.2
  #   command: --master zk://zookeeper:2181/mesos --zk_hosts zk://zookeeper:2181/mesos
  #   environment:
  #     PORT0: 8888
  #     PORT1: 8080
  #   ports:
  #     - 8888:8888
  #   depends_on:
  #     - zookeeper
  #     - mesos-master

  # metronome:
  #   image: mesoshq/metronome:0.2.0
  #   environment:
  #     metronome_mesos_master_url: mesosmaster:5050
  #     metronome_zk_url: zk://zookeeper:2181/mesos
  #     PORT0: 8081
  #     LIBPROCESS_IP: "0.0.0.0"
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - zookeeper
  #     - mesos-master
